-- 04_security_industry_access_load.sql
-- Fills the industry access table. Safe to re-run: it empties the table first.
-- Run by hand with care, because it changes who can see which rows.

TRUNCATE TABLE SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.ROLE_INDUSTRY_ACCESS;

INSERT INTO SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.ROLE_INDUSTRY_ACCESS (ROLE_NAME, INDUSTRY_DIVISION)
VALUES
    ('SEC_DATA_OWNER_ROLE',       '*'),
    ('SEC_ANALYST_ROLE',          '*'),
    ('SEC_PUBLIC_REPORTER_ROLE',  '*'),
    ('SEC_INDUSTRY_ANALYST_ROLE', 'Manufacturing'),
    ('SEC_INDUSTRY_ANALYST_ROLE', 'Retail Trade');

SELECT ROLE_NAME, INDUSTRY_DIVISION
FROM SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.ROLE_INDUSTRY_ACCESS
ORDER BY ROLE_NAME, INDUSTRY_DIVISION;