-- 01b_bronze_tables.sql
-- Bronze layer: the four SEC source tables.
-- All columns are text, exactly as received. Type conversion happens in silver.

-- Snowflake implementation reference:
-- This project was useful as a reference for separating the raw SEC data from the typed/transformed tables.
-- In it, the Bronze layer keeps the source values as text and type conversion is handled later.
--   https://github.com/BigDataIA-Spring2025-4/SEC-Bridge

-- Filing submissions (from sub.txt): one row per EDGAR filing (filer, form type, period, filing dates).
DEFINE TABLE SEC_FINANCIAL_DATA.BRONZE_SEC_FILINGS_STAGING.SOURCE_SEC_FILING_SUBMISSIONS (
  ADSH STRING, CIK STRING, NAME STRING, SIC STRING,
  COUNTRYBA STRING, STPRBA STRING, CITYBA STRING, ZIPBA STRING, BAS1 STRING, BAS2 STRING, BAPH STRING,
  COUNTRYMA STRING, STPRMA STRING, CITYMA STRING, ZIPMA STRING, MAS1 STRING, MAS2 STRING,
  COUNTRYINC STRING, STPRINC STRING, EIN STRING, FORMER STRING, CHANGED STRING,
  AFS STRING, WKSI STRING, FYE STRING, FORM STRING, PERIOD STRING, FY STRING, FP STRING,
  FILED STRING, ACCEPTED STRING, PREVRPT STRING, DETAIL STRING, INSTANCE STRING, NCIKS STRING, ACIKS STRING,
  SOURCE_QUARTER STRING,
  SOURCE_FILE_NAME STRING,
  LOADED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Financial values (from num.txt): one row per reported numeric value.
DEFINE TABLE SEC_FINANCIAL_DATA.BRONZE_SEC_FILINGS_STAGING.SOURCE_SEC_FINANCIAL_VALUES (
  ADSH STRING, TAG STRING, VERSION STRING, DDATE STRING, QTRS STRING, UOM STRING,
  SEGMENTS STRING, COREG STRING, VALUE STRING, FOOTNOTE STRING,
  SOURCE_QUARTER STRING,
  SOURCE_FILE_NAME STRING,
  LOADED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Tag definitions (from tag.txt): meaning of each standard and custom XBRL tag.
DEFINE TABLE SEC_FINANCIAL_DATA.BRONZE_SEC_FILINGS_STAGING.SOURCE_SEC_TAG_DEFINITIONS (
  TAG STRING, VERSION STRING, CUSTOM STRING, ABSTRACT STRING, DATATYPE STRING,
  IORD STRING, CRDR STRING, TLABEL STRING, DOC STRING,
  SOURCE_QUARTER STRING,
  SOURCE_FILE_NAME STRING,
  LOADED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Statement presentation (from pre.txt): where and how each tag appears on the financial statements.
DEFINE TABLE SEC_FINANCIAL_DATA.BRONZE_SEC_FILINGS_STAGING.SOURCE_SEC_STATEMENT_PRESENTATION (
  ADSH STRING, REPORT STRING, LINE STRING, STMT STRING, INPTH STRING, RFILE STRING,
  TAG STRING, VERSION STRING, PLABEL STRING, NEGATING STRING,
  SOURCE_QUARTER STRING,
  SOURCE_FILE_NAME STRING,
  LOADED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);