-- 01e_gold_facts.sql
-- Gold layer: fact tables. Each keeps keys to the dimensions in 01d_gold_dimensions.sql plus its own measures.
--   COMPANY_CIK -> DIM_COMPANY, INDUSTRY_SIC_CODE -> DIM_INDUSTRY, BUSINESS_STATE_CODE -> DIM_STATE,
--   FILER_SIZE_CODE -> DIM_FILER_SIZE, PERIOD_END_DATE -> DIM_DATE
-- A missing state or filer size is stored as NOT_STATED so every fact row has a match in its dimension.

-- Quarterly profitability: revenue, net income and net profit margin per company filing.
-- Built from 10-Q filings, using the value that covers the 3 months ending on the filing's period date.
DEFINE DYNAMIC TABLE SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.FACT_QUARTERLY_PROFITABILITY
  TARGET_LAG = '1 day'
  WAREHOUSE = SEC_FINANCIAL_DATA_PIPELINE_WAREHOUSE
AS
WITH filing_values AS (
    SELECT
        SOURCE_QUARTER,
        FILING_ACCESSION_NUMBER,
        COMPANY_CIK,
        INDUSTRY_SIC_CODE,
        BUSINESS_STATE_CODE,
        FILER_SIZE_CODE,
        FISCAL_YEAR,
        FISCAL_PERIOD,
        BALANCE_SHEET_DATE,
        COALESCE(
            MAX(CASE WHEN TAG_NAME = 'RevenueFromContractWithCustomerExcludingAssessedTax' THEN REPORTED_VALUE END),
            MAX(CASE WHEN TAG_NAME = 'Revenues' THEN REPORTED_VALUE END)
        )                                                               AS REVENUE_USD,
        MAX(CASE WHEN TAG_NAME = 'NetIncomeLoss' THEN REPORTED_VALUE END) AS NET_INCOME_USD
    FROM SEC_FINANCIAL_DATA.SILVER_SEC_INTEGRATED_FILINGS.SEC_FINANCIAL_FACTS_WITH_FILING_AND_TAG_DETAILS
    WHERE FORM_TYPE = '10-Q'
      AND QUARTERS_COVERED = 1
      AND VALUE_END_DATE = BALANCE_SHEET_DATE
      AND TAG_NAME IN ('RevenueFromContractWithCustomerExcludingAssessedTax', 'Revenues', 'NetIncomeLoss')
    GROUP BY SOURCE_QUARTER, FILING_ACCESSION_NUMBER, COMPANY_CIK, INDUSTRY_SIC_CODE,
             BUSINESS_STATE_CODE, FILER_SIZE_CODE, FISCAL_YEAR, FISCAL_PERIOD, BALANCE_SHEET_DATE
)
SELECT
    SOURCE_QUARTER,
    FILING_ACCESSION_NUMBER,
    COMPANY_CIK,
    INDUSTRY_SIC_CODE,
    COALESCE(BUSINESS_STATE_CODE, 'NOT_STATED')     AS BUSINESS_STATE_CODE,
    COALESCE(FILER_SIZE_CODE, 'NOT_STATED')         AS FILER_SIZE_CODE,
    FISCAL_YEAR,
    FISCAL_PERIOD,
    BALANCE_SHEET_DATE                              AS PERIOD_END_DATE,
    REVENUE_USD,
    NET_INCOME_USD,
    ROUND(NET_INCOME_USD / NULLIF(REVENUE_USD, 0) * 100, 2) AS NET_PROFIT_MARGIN_PERCENT
FROM filing_values
WHERE REVENUE_USD >= 1000000                -- drops revenue tags that capture only a small part of revenue
  AND NET_INCOME_USD IS NOT NULL
  AND NET_INCOME_USD <= REVENUE_USD;        -- net income above revenue is a tagging error





-- Quarterly financial position: total assets, total liabilities and equity at the period end date.
-- Built from 10-Q filings, using point-in-time values (QTRS = 0) dated on the filing's period date.
DEFINE DYNAMIC TABLE SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.FACT_QUARTERLY_FINANCIAL_POSITION
  TARGET_LAG = '1 day'
  WAREHOUSE = SEC_FINANCIAL_DATA_PIPELINE_WAREHOUSE
AS
WITH filing_values AS (
    SELECT
        SOURCE_QUARTER,
        FILING_ACCESSION_NUMBER,
        COMPANY_CIK,
        INDUSTRY_SIC_CODE,
        BUSINESS_STATE_CODE,
        FILER_SIZE_CODE,
        FISCAL_YEAR,
        FISCAL_PERIOD,
        BALANCE_SHEET_DATE,
        MAX(CASE WHEN TAG_NAME = 'Assets' THEN REPORTED_VALUE END)              AS TOTAL_ASSETS_USD,
        MAX(CASE WHEN TAG_NAME = 'Liabilities' THEN REPORTED_VALUE END)         AS TOTAL_LIABILITIES_USD,
        MAX(CASE WHEN TAG_NAME = 'StockholdersEquity' THEN REPORTED_VALUE END)  AS STOCKHOLDERS_EQUITY_USD
    FROM SEC_FINANCIAL_DATA.SILVER_SEC_INTEGRATED_FILINGS.SEC_FINANCIAL_FACTS_WITH_FILING_AND_TAG_DETAILS
    WHERE FORM_TYPE = '10-Q'
      AND QUARTERS_COVERED = 0
      AND VALUE_END_DATE = BALANCE_SHEET_DATE
      AND TAG_NAME IN ('Assets', 'Liabilities', 'StockholdersEquity')
    GROUP BY SOURCE_QUARTER, FILING_ACCESSION_NUMBER, COMPANY_CIK, INDUSTRY_SIC_CODE,
             BUSINESS_STATE_CODE, FILER_SIZE_CODE, FISCAL_YEAR, FISCAL_PERIOD, BALANCE_SHEET_DATE
)
SELECT
    SOURCE_QUARTER,
    FILING_ACCESSION_NUMBER,
    COMPANY_CIK,
    INDUSTRY_SIC_CODE,
    COALESCE(BUSINESS_STATE_CODE, 'NOT_STATED')     AS BUSINESS_STATE_CODE,
    COALESCE(FILER_SIZE_CODE, 'NOT_STATED')         AS FILER_SIZE_CODE,
    FISCAL_YEAR,
    FISCAL_PERIOD,
    BALANCE_SHEET_DATE                              AS PERIOD_END_DATE,
    TOTAL_ASSETS_USD,
    TOTAL_LIABILITIES_USD,
    STOCKHOLDERS_EQUITY_USD
FROM filing_values
WHERE TOTAL_ASSETS_USD > 0
  AND TOTAL_LIABILITIES_USD IS NOT NULL;





-- Filing: one row per filing, with how many days after the period end it was filed.
-- Covers every form type in the silver table, not only 10-Q.
DEFINE DYNAMIC TABLE SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.FACT_FILING
  TARGET_LAG = '1 day'
  WAREHOUSE = SEC_FINANCIAL_DATA_PIPELINE_WAREHOUSE
AS
WITH filing_values AS (
    SELECT
        SOURCE_QUARTER,
        FILING_ACCESSION_NUMBER,
        COMPANY_CIK,
        INDUSTRY_SIC_CODE,
        BUSINESS_STATE_CODE,
        FILER_SIZE_CODE,
        FORM_TYPE,
        FISCAL_YEAR,
        FISCAL_PERIOD,
        BALANCE_SHEET_DATE,
        FILING_DATE,
        COUNT(*) AS REPORTED_VALUES_COUNT
    FROM SEC_FINANCIAL_DATA.SILVER_SEC_INTEGRATED_FILINGS.SEC_FINANCIAL_FACTS_WITH_FILING_AND_TAG_DETAILS
    GROUP BY SOURCE_QUARTER, FILING_ACCESSION_NUMBER, COMPANY_CIK, INDUSTRY_SIC_CODE,
             BUSINESS_STATE_CODE, FILER_SIZE_CODE, FORM_TYPE, FISCAL_YEAR, FISCAL_PERIOD,
             BALANCE_SHEET_DATE, FILING_DATE
)
SELECT
    SOURCE_QUARTER,
    FILING_ACCESSION_NUMBER,
    COMPANY_CIK,
    INDUSTRY_SIC_CODE,
    COALESCE(BUSINESS_STATE_CODE, 'NOT_STATED')     AS BUSINESS_STATE_CODE,
    COALESCE(FILER_SIZE_CODE, 'NOT_STATED')         AS FILER_SIZE_CODE,
    FORM_TYPE,
    FISCAL_YEAR,
    FISCAL_PERIOD,
    BALANCE_SHEET_DATE                              AS PERIOD_END_DATE,
    FILING_DATE,
    DATEDIFF('day', BALANCE_SHEET_DATE, FILING_DATE) AS DAYS_FROM_PERIOD_END_TO_FILING,
    REPORTED_VALUES_COUNT
FROM filing_values;