-- 04_security_roles_and_grants.sql
-- Access control for the gold layer.
-- Roles are one per audience. Only the data owner reads the gold tables directly.
-- All other roles read secure report views, granted in the report view files.
-- Horizontal split (rows): ROLE_INDUSTRY_ACCESS lists which industry divisions each role may see.
-- Vertical split (columns): the public reporter role is given views without the dollar columns.

-- Roles
DEFINE ROLE SEC_DATA_OWNER_ROLE;
DEFINE ROLE SEC_ANALYST_ROLE;
DEFINE ROLE SEC_INDUSTRY_ANALYST_ROLE;
DEFINE ROLE SEC_PUBLIC_REPORTER_ROLE;

-- Industry access table: which industry divisions each role may see. '*' means all divisions.
-- Filled by scripts/04_security_industry_access_load.sql.
DEFINE TABLE SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.ROLE_INDUSTRY_ACCESS (
  ROLE_NAME STRING,
  INDUSTRY_DIVISION STRING
);

-- Compute: every role can run queries on the pipeline warehouse.
GRANT USAGE ON WAREHOUSE SEC_FINANCIAL_DATA_PIPELINE_WAREHOUSE TO ROLE SEC_DATA_OWNER_ROLE;
GRANT USAGE ON WAREHOUSE SEC_FINANCIAL_DATA_PIPELINE_WAREHOUSE TO ROLE SEC_ANALYST_ROLE;
GRANT USAGE ON WAREHOUSE SEC_FINANCIAL_DATA_PIPELINE_WAREHOUSE TO ROLE SEC_INDUSTRY_ANALYST_ROLE;
GRANT USAGE ON WAREHOUSE SEC_FINANCIAL_DATA_PIPELINE_WAREHOUSE TO ROLE SEC_PUBLIC_REPORTER_ROLE;

-- Database and gold schema: every role can see the gold schema, but not read its tables.
GRANT USAGE ON DATABASE SEC_FINANCIAL_DATA TO ROLE SEC_DATA_OWNER_ROLE;
GRANT USAGE ON DATABASE SEC_FINANCIAL_DATA TO ROLE SEC_ANALYST_ROLE;
GRANT USAGE ON DATABASE SEC_FINANCIAL_DATA TO ROLE SEC_INDUSTRY_ANALYST_ROLE;
GRANT USAGE ON DATABASE SEC_FINANCIAL_DATA TO ROLE SEC_PUBLIC_REPORTER_ROLE;

GRANT USAGE ON SCHEMA SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING TO ROLE SEC_DATA_OWNER_ROLE;
GRANT USAGE ON SCHEMA SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING TO ROLE SEC_ANALYST_ROLE;
GRANT USAGE ON SCHEMA SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING TO ROLE SEC_INDUSTRY_ANALYST_ROLE;
GRANT USAGE ON SCHEMA SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING TO ROLE SEC_PUBLIC_REPORTER_ROLE;

-- Data owner also sees the bronze and silver schemas, for the load checks.
GRANT USAGE ON SCHEMA SEC_FINANCIAL_DATA.BRONZE_SEC_FILINGS_STAGING TO ROLE SEC_DATA_OWNER_ROLE;
GRANT USAGE ON SCHEMA SEC_FINANCIAL_DATA.SILVER_SEC_INTEGRATED_FILINGS TO ROLE SEC_DATA_OWNER_ROLE;

-- Test access: lets the project owner switch to each role.
GRANT ROLE SEC_DATA_OWNER_ROLE TO USER PRADYUMNASHEE;
GRANT ROLE SEC_ANALYST_ROLE TO USER PRADYUMNASHEE;
GRANT ROLE SEC_INDUSTRY_ANALYST_ROLE TO USER PRADYUMNASHEE;
GRANT ROLE SEC_PUBLIC_REPORTER_ROLE TO USER PRADYUMNASHEE;

-- Data owner reads everything below the report views: gold, silver and bronze tables.
GRANT SELECT ON DYNAMIC TABLE SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.DIM_COMPANY TO ROLE SEC_DATA_OWNER_ROLE;
GRANT SELECT ON DYNAMIC TABLE SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.DIM_INDUSTRY TO ROLE SEC_DATA_OWNER_ROLE;
GRANT SELECT ON DYNAMIC TABLE SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.DIM_FILER_SIZE TO ROLE SEC_DATA_OWNER_ROLE;
GRANT SELECT ON DYNAMIC TABLE SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.DIM_STATE TO ROLE SEC_DATA_OWNER_ROLE;
GRANT SELECT ON DYNAMIC TABLE SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.DIM_DATE TO ROLE SEC_DATA_OWNER_ROLE;
GRANT SELECT ON DYNAMIC TABLE SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.FACT_QUARTERLY_PROFITABILITY TO ROLE SEC_DATA_OWNER_ROLE;
GRANT SELECT ON DYNAMIC TABLE SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.FACT_QUARTERLY_FINANCIAL_POSITION TO ROLE SEC_DATA_OWNER_ROLE;
GRANT SELECT ON DYNAMIC TABLE SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.FACT_FILING TO ROLE SEC_DATA_OWNER_ROLE;
GRANT SELECT ON TABLE SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.ROLE_INDUSTRY_ACCESS TO ROLE SEC_DATA_OWNER_ROLE;
GRANT SELECT ON DYNAMIC TABLE SEC_FINANCIAL_DATA.SILVER_SEC_INTEGRATED_FILINGS.SEC_FINANCIAL_FACTS_WITH_FILING_AND_TAG_DETAILS TO ROLE SEC_DATA_OWNER_ROLE;
GRANT SELECT ON TABLE SEC_FINANCIAL_DATA.BRONZE_SEC_FILINGS_STAGING.SOURCE_SEC_FILING_SUBMISSIONS TO ROLE SEC_DATA_OWNER_ROLE;
GRANT SELECT ON TABLE SEC_FINANCIAL_DATA.BRONZE_SEC_FILINGS_STAGING.SOURCE_SEC_FINANCIAL_VALUES TO ROLE SEC_DATA_OWNER_ROLE;
GRANT SELECT ON TABLE SEC_FINANCIAL_DATA.BRONZE_SEC_FILINGS_STAGING.SOURCE_SEC_TAG_DEFINITIONS TO ROLE SEC_DATA_OWNER_ROLE;
GRANT SELECT ON TABLE SEC_FINANCIAL_DATA.BRONZE_SEC_FILINGS_STAGING.SOURCE_SEC_STATEMENT_PRESENTATION TO ROLE SEC_DATA_OWNER_ROLE;