-- 06_report_industry_profitability.sql
-- Report A: who makes money, by industry division and calendar quarter.
-- Built from FACT_QUARTERLY_PROFITABILITY, DIM_INDUSTRY and DIM_DATE.
-- Both views are secure views. Rows are limited by ROLE_INDUSTRY_ACCESS (horizontal split).
-- The public view leaves out the dollar columns (vertical split).
-- Test with USE ROLE ...; the project owner role ACCOUNTADMIN is not in the access table and sees no rows.

-- Full view: includes total revenue and total net income in dollars.
DEFINE SECURE VIEW SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.REPORT_INDUSTRY_PROFITABILITY
AS
SELECT
    i.INDUSTRY_DIVISION,
    d.CALENDAR_YEAR_QUARTER,
    COUNT(DISTINCT f.COMPANY_CIK)                                   AS COMPANY_COUNT,
    ROUND(100 * COUNT_IF(f.NET_INCOME_USD > 0) / COUNT(*), 1)       AS PROFITABLE_COMPANY_PERCENT,
    SUM(f.REVENUE_USD)                                              AS TOTAL_REVENUE_USD,
    SUM(f.NET_INCOME_USD)                                           AS TOTAL_NET_INCOME_USD,
    ROUND(100 * SUM(f.NET_INCOME_USD) / NULLIF(SUM(f.REVENUE_USD), 0), 2) AS AGGREGATE_MARGIN_PERCENT,
    ROUND(MEDIAN(f.NET_PROFIT_MARGIN_PERCENT), 2)                   AS MEDIAN_MARGIN_PERCENT
FROM SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.FACT_QUARTERLY_PROFITABILITY f
JOIN SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.DIM_INDUSTRY i ON f.INDUSTRY_SIC_CODE = i.INDUSTRY_SIC_CODE
JOIN SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.DIM_DATE d     ON f.PERIOD_END_DATE = d.PERIOD_END_DATE
WHERE EXISTS (
    SELECT 1
    FROM SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.ROLE_INDUSTRY_ACCESS a
    WHERE IS_ROLE_IN_SESSION(a.ROLE_NAME)
      AND (a.INDUSTRY_DIVISION = '*' OR a.INDUSTRY_DIVISION = i.INDUSTRY_DIVISION)
)
GROUP BY i.INDUSTRY_DIVISION, d.CALENDAR_YEAR_QUARTER
HAVING COUNT(DISTINCT f.COMPANY_CIK) >= 10;

-- Public view: same rows, no dollar columns.
DEFINE SECURE VIEW SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.REPORT_INDUSTRY_PROFITABILITY_PUBLIC
AS
SELECT
    i.INDUSTRY_DIVISION,
    d.CALENDAR_YEAR_QUARTER,
    COUNT(DISTINCT f.COMPANY_CIK)                                   AS COMPANY_COUNT,
    ROUND(100 * COUNT_IF(f.NET_INCOME_USD > 0) / COUNT(*), 1)       AS PROFITABLE_COMPANY_PERCENT,
    ROUND(100 * SUM(f.NET_INCOME_USD) / NULLIF(SUM(f.REVENUE_USD), 0), 2) AS AGGREGATE_MARGIN_PERCENT,
    ROUND(MEDIAN(f.NET_PROFIT_MARGIN_PERCENT), 2)                   AS MEDIAN_MARGIN_PERCENT
FROM SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.FACT_QUARTERLY_PROFITABILITY f
JOIN SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.DIM_INDUSTRY i ON f.INDUSTRY_SIC_CODE = i.INDUSTRY_SIC_CODE
JOIN SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.DIM_DATE d     ON f.PERIOD_END_DATE = d.PERIOD_END_DATE
WHERE EXISTS (
    SELECT 1
    FROM SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.ROLE_INDUSTRY_ACCESS a
    WHERE IS_ROLE_IN_SESSION(a.ROLE_NAME)
      AND (a.INDUSTRY_DIVISION = '*' OR a.INDUSTRY_DIVISION = i.INDUSTRY_DIVISION)
)
GROUP BY i.INDUSTRY_DIVISION, d.CALENDAR_YEAR_QUARTER
HAVING COUNT(DISTINCT f.COMPANY_CIK) >= 10;

-- Grants: the full view is for the data owner, analyst and industry analyst roles.
GRANT SELECT ON VIEW SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.REPORT_INDUSTRY_PROFITABILITY TO ROLE SEC_DATA_OWNER_ROLE;
GRANT SELECT ON VIEW SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.REPORT_INDUSTRY_PROFITABILITY TO ROLE SEC_ANALYST_ROLE;
GRANT SELECT ON VIEW SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.REPORT_INDUSTRY_PROFITABILITY TO ROLE SEC_INDUSTRY_ANALYST_ROLE;

-- The public view is for all four roles.
GRANT SELECT ON VIEW SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.REPORT_INDUSTRY_PROFITABILITY_PUBLIC TO ROLE SEC_DATA_OWNER_ROLE;
GRANT SELECT ON VIEW SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.REPORT_INDUSTRY_PROFITABILITY_PUBLIC TO ROLE SEC_ANALYST_ROLE;
GRANT SELECT ON VIEW SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.REPORT_INDUSTRY_PROFITABILITY_PUBLIC TO ROLE SEC_INDUSTRY_ANALYST_ROLE;
GRANT SELECT ON VIEW SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.REPORT_INDUSTRY_PROFITABILITY_PUBLIC TO ROLE SEC_PUBLIC_REPORTER_ROLE;