-- 07_report_filer_size_profitability.sql
-- Report B: Compares company profitability based on company size and calendar quarter.
--
-- It groups companies into SEC filer-size categories and calculates revenue, net income and profit margin for each group.
-- The report uses quarterly profitability data together with filer-size, industry and calendar information.
-- Access is still controlled by industry, as in Report A. This means a user can only see the filer-size results for industries they are allowed to access.
-- Groups with fewer than 10 companies are excluded so that results are not based on very small groups.
-- The public view shows the profitability measures and percentages, but does not expose the underlying dollar amounts.

-- Full view: includes total revenue and total net income in dollars.
DEFINE SECURE VIEW SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.REPORT_FILER_SIZE_PROFITABILITY
AS
SELECT
    fs.FILER_SIZE_NAME,
    d.CALENDAR_YEAR_QUARTER,
    COUNT(DISTINCT f.COMPANY_CIK)                                   AS COMPANY_COUNT,
    ROUND(100 * COUNT_IF(f.NET_INCOME_USD > 0) / COUNT(*), 1)       AS PROFITABLE_COMPANY_PERCENT,
    SUM(f.REVENUE_USD)                                              AS TOTAL_REVENUE_USD,
    SUM(f.NET_INCOME_USD)                                           AS TOTAL_NET_INCOME_USD,
    ROUND(100 * SUM(f.NET_INCOME_USD) / NULLIF(SUM(f.REVENUE_USD), 0), 2) AS AGGREGATE_MARGIN_PERCENT,
    ROUND(MEDIAN(f.NET_PROFIT_MARGIN_PERCENT), 2)                   AS MEDIAN_MARGIN_PERCENT
FROM SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.FACT_QUARTERLY_PROFITABILITY f
JOIN SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.DIM_FILER_SIZE fs ON f.FILER_SIZE_CODE = fs.FILER_SIZE_CODE
JOIN SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.DIM_INDUSTRY i    ON f.INDUSTRY_SIC_CODE = i.INDUSTRY_SIC_CODE
JOIN SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.DIM_DATE d       ON f.PERIOD_END_DATE = d.PERIOD_END_DATE
WHERE EXISTS (
    SELECT 1
    FROM SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.ROLE_INDUSTRY_ACCESS a
    WHERE IS_ROLE_IN_SESSION(a.ROLE_NAME)
      AND (a.INDUSTRY_DIVISION = '*' OR a.INDUSTRY_DIVISION = i.INDUSTRY_DIVISION)
)
GROUP BY fs.FILER_SIZE_NAME, d.CALENDAR_YEAR_QUARTER
HAVING COUNT(DISTINCT f.COMPANY_CIK) >= 10;

-- Public view: same rows, no dollar columns.
DEFINE SECURE VIEW SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.REPORT_FILER_SIZE_PROFITABILITY_PUBLIC
AS
SELECT
    fs.FILER_SIZE_NAME,
    d.CALENDAR_YEAR_QUARTER,
    COUNT(DISTINCT f.COMPANY_CIK)                                   AS COMPANY_COUNT,
    ROUND(100 * COUNT_IF(f.NET_INCOME_USD > 0) / COUNT(*), 1)       AS PROFITABLE_COMPANY_PERCENT,
    ROUND(100 * SUM(f.NET_INCOME_USD) / NULLIF(SUM(f.REVENUE_USD), 0), 2) AS AGGREGATE_MARGIN_PERCENT,
    ROUND(MEDIAN(f.NET_PROFIT_MARGIN_PERCENT), 2)                   AS MEDIAN_MARGIN_PERCENT
FROM SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.FACT_QUARTERLY_PROFITABILITY f
JOIN SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.DIM_FILER_SIZE fs ON f.FILER_SIZE_CODE = fs.FILER_SIZE_CODE
JOIN SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.DIM_INDUSTRY i    ON f.INDUSTRY_SIC_CODE = i.INDUSTRY_SIC_CODE
JOIN SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.DIM_DATE d       ON f.PERIOD_END_DATE = d.PERIOD_END_DATE
WHERE EXISTS (
    SELECT 1
    FROM SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.ROLE_INDUSTRY_ACCESS a
    WHERE IS_ROLE_IN_SESSION(a.ROLE_NAME)
      AND (a.INDUSTRY_DIVISION = '*' OR a.INDUSTRY_DIVISION = i.INDUSTRY_DIVISION)
)
GROUP BY fs.FILER_SIZE_NAME, d.CALENDAR_YEAR_QUARTER
HAVING COUNT(DISTINCT f.COMPANY_CIK) >= 10;

-- Grants: same pattern as Report A.
GRANT SELECT ON VIEW SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.REPORT_FILER_SIZE_PROFITABILITY TO ROLE SEC_DATA_OWNER_ROLE;
GRANT SELECT ON VIEW SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.REPORT_FILER_SIZE_PROFITABILITY TO ROLE SEC_ANALYST_ROLE;
GRANT SELECT ON VIEW SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.REPORT_FILER_SIZE_PROFITABILITY TO ROLE SEC_INDUSTRY_ANALYST_ROLE;

GRANT SELECT ON VIEW SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.REPORT_FILER_SIZE_PROFITABILITY_PUBLIC TO ROLE SEC_DATA_OWNER_ROLE;
GRANT SELECT ON VIEW SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.REPORT_FILER_SIZE_PROFITABILITY_PUBLIC TO ROLE SEC_ANALYST_ROLE;
GRANT SELECT ON VIEW SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.REPORT_FILER_SIZE_PROFITABILITY_PUBLIC TO ROLE SEC_INDUSTRY_ANALYST_ROLE;
GRANT SELECT ON VIEW SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.REPORT_FILER_SIZE_PROFITABILITY_PUBLIC TO ROLE SEC_PUBLIC_REPORTER_ROLE;