-- 08_report_state_profitability.sql
-- Report C: where the profits are, by US state and calendar quarter.
-- Built from FACT_QUARTERLY_PROFITABILITY, DIM_STATE, DIM_INDUSTRY and DIM_DATE.
-- Rows are still limited by industry division (ROLE_INDUSTRY_ACCESS), same as Reports A and B.
-- Companies with no stated state, or a non-US business address, are left out. A map can only place a US state.
-- Groups with fewer than 10 companies are dropped, same rule as Reports A and B.
-- The public view leaves out the dollar column.

-- Full view: includes total net income in dollars.
DEFINE SECURE VIEW SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.REPORT_STATE_PROFITABILITY
AS
SELECT
    s.BUSINESS_STATE_NAME,
    d.CALENDAR_YEAR_QUARTER,
    COUNT(DISTINCT f.COMPANY_CIK)                             AS COMPANY_COUNT,
    ROUND(100 * COUNT_IF(f.NET_INCOME_USD > 0) / COUNT(*), 1)  AS PROFITABLE_COMPANY_PERCENT,
    SUM(f.NET_INCOME_USD)                                     AS TOTAL_NET_INCOME_USD
FROM SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.FACT_QUARTERLY_PROFITABILITY f
JOIN SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.DIM_STATE s    ON f.BUSINESS_STATE_CODE = s.BUSINESS_STATE_CODE
JOIN SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.DIM_INDUSTRY i ON f.INDUSTRY_SIC_CODE = i.INDUSTRY_SIC_CODE
JOIN SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.DIM_DATE d     ON f.PERIOD_END_DATE = d.PERIOD_END_DATE
WHERE s.BUSINESS_STATE_NAME NOT IN ('Not stated', 'Outside the United States')
  AND EXISTS (
    SELECT 1
    FROM SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.ROLE_INDUSTRY_ACCESS a
    WHERE IS_ROLE_IN_SESSION(a.ROLE_NAME)
      AND (a.INDUSTRY_DIVISION = '*' OR a.INDUSTRY_DIVISION = i.INDUSTRY_DIVISION)
  )
GROUP BY s.BUSINESS_STATE_NAME, d.CALENDAR_YEAR_QUARTER
HAVING COUNT(DISTINCT f.COMPANY_CIK) >= 10;

-- Public view: same rows, no dollar column.
DEFINE SECURE VIEW SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.REPORT_STATE_PROFITABILITY_PUBLIC
AS
SELECT
    s.BUSINESS_STATE_NAME,
    d.CALENDAR_YEAR_QUARTER,
    COUNT(DISTINCT f.COMPANY_CIK)                             AS COMPANY_COUNT,
    ROUND(100 * COUNT_IF(f.NET_INCOME_USD > 0) / COUNT(*), 1)  AS PROFITABLE_COMPANY_PERCENT
FROM SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.FACT_QUARTERLY_PROFITABILITY f
JOIN SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.DIM_STATE s    ON f.BUSINESS_STATE_CODE = s.BUSINESS_STATE_CODE
JOIN SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.DIM_INDUSTRY i ON f.INDUSTRY_SIC_CODE = i.INDUSTRY_SIC_CODE
JOIN SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.DIM_DATE d     ON f.PERIOD_END_DATE = d.PERIOD_END_DATE
WHERE s.BUSINESS_STATE_NAME NOT IN ('Not stated', 'Outside the United States')
  AND EXISTS (
    SELECT 1
    FROM SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.ROLE_INDUSTRY_ACCESS a
    WHERE IS_ROLE_IN_SESSION(a.ROLE_NAME)
      AND (a.INDUSTRY_DIVISION = '*' OR a.INDUSTRY_DIVISION = i.INDUSTRY_DIVISION)
  )
GROUP BY s.BUSINESS_STATE_NAME, d.CALENDAR_YEAR_QUARTER
HAVING COUNT(DISTINCT f.COMPANY_CIK) >= 10;

-- Grants: same pattern as Reports A and B.
GRANT SELECT ON VIEW SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.REPORT_STATE_PROFITABILITY TO ROLE SEC_DATA_OWNER_ROLE;
GRANT SELECT ON VIEW SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.REPORT_STATE_PROFITABILITY TO ROLE SEC_ANALYST_ROLE;
GRANT SELECT ON VIEW SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.REPORT_STATE_PROFITABILITY TO ROLE SEC_INDUSTRY_ANALYST_ROLE;

GRANT SELECT ON VIEW SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.REPORT_STATE_PROFITABILITY_PUBLIC TO ROLE SEC_DATA_OWNER_ROLE;
GRANT SELECT ON VIEW SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.REPORT_STATE_PROFITABILITY_PUBLIC TO ROLE SEC_ANALYST_ROLE;
GRANT SELECT ON VIEW SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.REPORT_STATE_PROFITABILITY_PUBLIC TO ROLE SEC_INDUSTRY_ANALYST_ROLE;
GRANT SELECT ON VIEW SEC_FINANCIAL_DATA.GOLD_SEC_ANALYTICS_REPORTING.REPORT_STATE_PROFITABILITY_PUBLIC TO ROLE SEC_PUBLIC_REPORTER_ROLE;
